name: Build WASM
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Emscripten and Build
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          ./emsdk/emsdk install latest
          ./emsdk/emsdk activate latest
          source ./emsdk/emsdk_env.sh
          emcc main.c -O3 \
          -s EXPORTED_FUNCTIONS=_main \
          -s ENVIRONMENT=web \
          -s MODULARIZE=1 \
          -s EXPORT_ES6=1 \
          -s ALLOW_MEMORY_GROWTH=1 \
          -s EXIT_RUNTIME=1 \
          -s NO_FILESYSTEM=0 \
          -o ext/ries.js
      - name: Commit and push build output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ext/ries.*
          git commit -m "Build WASM artifact"
          git push
